#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#
#  h2:
#    console:
#      enabled: true
#
#  servlet:
#    multipart:
#      file-size-threshold: 2KB
#      max-file-size: 200MB
#      max-request-size: 215MB

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_demo
    username: raga
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: st
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
